id: string
title: string
description:
    -
        plain_text: string
category_id: string
price: number
currency_id: string
buying_mode: string
listing_type_id: string
condition: string
pictures:
    -
        id: string
        url: string
        secure_url: string
        size: string
        max_size: string
        quality: string
available_quantity: number
shipping: array
official_store_id: number
status: string
